version: '3.8'
services:
  simulator_container:
    build: ./simulator
    depends_on:
      - api_container
    networks:
      - mynetwork

  api_container:
    build: ./api
    depends_on:
      - redis_container1
      - redis_container2
      - redis_container3
      - redis_container4
      - grpc_container
    networks:
      - mynetwork
    ports:
      - "5000:5000"

  redis_container1:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mynetwork
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "", "--maxmemory", "1mb", "--maxmemory-policy", "allkeys-lfu", "--protected-mode", "no"]

  redis_container2:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mynetwork
    ports:
      - "6380:6379"
    command: ["redis-server", "--port", "6380", "--save", "", "--maxmemory", "1mb", "--maxmemory-policy", "allkeys-lfu", "--protected-mode", "no"]

  redis_container3:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mynetwork
    ports:
      - "6381:6379"
    command: ["redis-server", "--port", "6381", "--save", "", "--maxmemory", "1mb", "--maxmemory-policy", "allkeys-lfu", "--protected-mode", "no"]

  redis_container4:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - mynetwork
    ports:
      - "6382:6379"
    command: ["redis-server", "--port", "6382", "--save", "", "--maxmemory", "1mb", "--maxmemory-policy", "allkeys-lfu", "--protected-mode", "no"] 

  grpc_container:
    build: ./grpc_server
    networks:
      - mynetwork
    ports:
      - "50051:50051"

networks:
  mynetwork:
    driver: bridge
